# Name: Aniruddh Kulkarni

# Roll No: I081

# Batch: C3

# Semester: III Semester

# Branch: CS(AI)

# Date of Experiment: 31-07-2021

# Subject: Random Processes and Estimation Techniques



**: Aim of the experiment**

1.  Write a program to generate Joint Prob. Distribution table  of the following Joint PMF,

 $$ f(x)=\frac{x^2y}{140} $$           

Further obtain,



a.  Marginal PMF of x and y



b.  Mean and variance of x and y



c.  Coefficient of correlation

# Write a program to generate Joint Prob. Distribution table of the following 

Joint PMF, 

$$ f(x)=\frac{x^2 y}{140} $$

$$ x = 1,2,3 \hspace{10mm} y = 1,2,3,4$$
Further obtain,

a. Marginal PMF of x and y

b. Mean and variance of x and y

c. Coefficient of correlation

In [35]:
import numpy as np

In [36]:
def matrix(p,q):
    global z
    z=np.zeros((p,q))
    for x in range(p):
        for y in range(q):
            z[x,y]=(((x+1)**2)*(y+1))/140
    print(z)
    print('sum of matrix elements=',np.sum(z))
    

# a. Marginal PMF of x and y

In [37]:
# pmf_y=np.sum(z,axis=0) 
# pmf_x=np.sum(z,axis=1) 
def pmfx():
    global pmf_x
    pmf_x=np.sum(z,axis=1)
    print('PMF(X) is as Follows=')
    print("x : p(x)")
    for i,x in enumerate(pmf_x):
        print(i,':',np.round_(x,decimals=2))
        print('\n')
    return ''

def pmfy():
    global pmf_y
    print('PMF(Y) is as Follows=')
    pmf_y=np.sum(z,axis=0)
    print("y : p(y)")
    for i,y in enumerate(pmf_y):
        print(i,':',np.round_(y,decimals=2))
    return ''

# b. Mean and Variance of x and y

In [38]:
def mve():
    #mean and variance of x
    global m_x 
    global var_x
    m_x=0 
    ex_x=0
    var_x=0
    for i in range(1,4):
        m_x+= (i*pmf_x[i-1])
        ex_x+= (i*i*pmf_x[i-1]) 
        var_x = ex_x-(m_x**2)
    print("mean       of x:", np.round(m_x,decimals=3))
    print("Expectance of x:", np.round(ex_x,decimals=3))
    print("variance   of x:",np.round(var_x,decimals=3))

    print('\t')
    
    #mean and variance of y
    global m_y 
    global var_y
    m_y=0 
    ex_y=0
    var_y=0
    for i in range(1,5):
        m_y+= (i*pmf_y[i-1])
        ex_y+= (i*i*pmf_y[i-1]) 
        var_y = ex_y-(m_y**2)
    print("mean       of y:", np.round(m_y,decimals=3))
    print("Expectance of y:", np.round(ex_y,decimals=3))
    print("variance   of y:", np.round(var_y,decimals=3))

# c. Coefficient of correlation 

$$r = \frac{E(xy) - E(x)E(y)}{(V(x)V(y))^{1/2}}$$

In [39]:
def corr():
    global m_x
    global m_y
    global var_x
    global var_y
    global E_xy
    global e_xy
    global r
    E_xy=0
    for (x,y), pmf_xy in np.ndenumerate(z):
        e_xy = (x+1)*(y+1)*pmf_xy
        E_xy+=e_xy
    #correlation    
    print("correlation of X:",np.round(E_xy,decimals=3))
    # COefficient
    r = (E_xy-m_x*m_y)/(np.sqrt(var_x)*np.sqrt(var_y))
    print(r)

In [40]:
# Menu Driven Code
ch=int(input('choose choice: \n 0. Matix \n 1.Pmf(x) \n 2.Pmf(y) \n 3.Mean,Variance,Expectance \n 4.Correlation'))
if (ch==0):
    p=int(input('Enter value for x in matrix='))
    q =int(input('Enter value for y in matrix='))
    matrix(p,q)           
elif (ch==1):
    pmfx()
elif (ch==2):
    pmfy()
elif (ch==3):
    mve()
elif (ch==4):
    corr()
else:
    quit()

choose choice: 
 0. Matix 
 1.Pmf(x) 
 2.Pmf(y) 
 3.Mean,Variance,Expectance 
 4.Correlation0
Enter value for x in matrix=3
Enter value for y in matrix=4
[[0.00714286 0.01428571 0.02142857 0.02857143]
 [0.02857143 0.05714286 0.08571429 0.11428571]
 [0.06428571 0.12857143 0.19285714 0.25714286]]
sum of matrix elements= 0.9999999999999999


In [41]:
pmfx()
pmfy()
print('\n')
mve()
print('\n')
corr()

PMF(X) is as Follows=
x : p(x)
0 : 0.07


1 : 0.29


2 : 0.64


PMF(Y) is as Follows=
y : p(y)
0 : 0.1
1 : 0.2
2 : 0.3
3 : 0.4


mean       of x: 2.571
Expectance of x: 7.0
variance   of x: 0.388
	
mean       of y: 3.0
Expectance of y: 10.0
variance   of y: 1.0


correlation of X: 7.714
0.0


# Conclusion

I understood Marginal PMF, Mean & Variance and also the coefficient of correlation and implemented them using python.

I also learnt to use Numpy modules to create 2D arrays 

